-- SENATRAN mock — contract read views. GENERATED by tools/scripts/generate-views.ts.
-- Do not edit by hand; run `pnpm views:generate`.

-- GET /v1/autorizacoesAlteracaoVeiculo/alteracoesPermitidas
create or replace view contract.v_alteracoes_permitidas as
  select coalesce(jsonb_agg(payload order by id), '[]'::jsonb) as payload
  from senatran.alteracao_permitida;

-- GET /v1/condutores/cpf/{cpf}
create or replace view contract.v_condutores_by_cpf as
  select cpf, jsonb_build_object('condutores', coalesce(jsonb_agg(payload order by id), '[]'::jsonb)) as payload
  from senatran.condutor
  group by cpf;

-- GET /v1/condutores/cpf/{cpf}/registroCnh/{numeroRegistroCnh}
create or replace view contract.v_condutores_by_cpf_and_registro_cnh as
  select cpf, numero_registro, jsonb_build_object('condutores', coalesce(jsonb_agg(payload order by id), '[]'::jsonb)) as payload
  from senatran.condutor
  group by cpf, numero_registro;

-- GET /v1/condutores/formularioRenach/{formularioRenach}
create or replace view contract.v_condutores_by_formulario_renach as
  select numero_formulario_renach, jsonb_build_object('condutores', coalesce(jsonb_agg(payload order by id), '[]'::jsonb)) as payload
  from senatran.condutor
  group by numero_formulario_renach;

-- GET /v1/condutores/imagens/cpf/{cpf}/registroCnh/{numeroRegistro}/segurancaCnh/{numeroSeguranca}
create or replace view contract.v_condutor_imagens_by_cpf_registro_cnh_seguranca as
  select cpf, numero_registro, numero_seguranca, payload
  from senatran.condutor_imagem;

-- GET /v1/condutores/impedimento/{impedimento}
create or replace view contract.v_condutores_by_impedimento as
  select numero_lista_impedimento, jsonb_build_object('condutores', coalesce(jsonb_agg(payload order by id), '[]'::jsonb)) as payload
  from senatran.condutor
  group by numero_lista_impedimento;

-- GET /v1/condutores/infracoes/registroCnh/{numeroRegistroCnh}
create or replace view contract.v_condutor_infracoes_by_registro_cnh as
  select numero_registro_cnh, jsonb_build_object('quantidade', count(*), 'quantidadeReal', count(*), 'ocorrencias', coalesce(jsonb_agg(payload order by id), '[]'::jsonb)) as payload
  from senatran.condutor_infracao_item
  group by numero_registro_cnh;

-- GET /v1/condutores/nomeCondutor/{nomeCondutor}/dataNascimento/{dataNascimento}/nomeMae/{nomeMae}
create or replace view contract.v_condutores_by_dados_identificatorios as
  select nome, data_nascimento, nome_mae, jsonb_build_object('condutores', coalesce(jsonb_agg(payload order by id), '[]'::jsonb)) as payload
  from senatran.condutor
  group by nome, data_nascimento, nome_mae;

-- GET /v1/condutores/pgu/{pgu}
create or replace view contract.v_condutores_by_pgu as
  select numero_pgu, jsonb_build_object('condutores', coalesce(jsonb_agg(payload order by id), '[]'::jsonb)) as payload
  from senatran.condutor
  group by numero_pgu;

-- GET /v1/condutores/pid/{pid}
create or replace view contract.v_condutores_by_pid as
  select numero_formulario_pid, jsonb_build_object('condutores', coalesce(jsonb_agg(payload order by id), '[]'::jsonb)) as payload
  from senatran.condutor
  group by numero_formulario_pid;

-- GET /v1/condutores/registroCnh/{numeroRegistroCnh}
create or replace view contract.v_condutores_by_registro_cnh as
  select numero_registro, jsonb_build_object('condutores', coalesce(jsonb_agg(payload order by id), '[]'::jsonb)) as payload
  from senatran.condutor
  group by numero_registro;

-- GET /v1/condutores/retrato/cpf/{cpf}/registroCnh/{numeroRegistro}/segurancaCnh/{numeroSeguranca}
create or replace view contract.v_condutor_retrato_by_cpf_registro_cnh_seguranca as
  select cpf, numero_registro, numero_seguranca, payload
  from senatran.condutor_imagem;

-- GET /v1/condutores/validacao/cpf/{cpf}/registroCnh/{numeroRegistro}/segurancaCnh/{numeroSeguranca}
create or replace view contract.v_condutor_validacao_by_cpf_registro_cnh_seguranca as
  select cpf, numero_registro, numero_seguranca, payload
  from senatran.condutor_imagem;

-- GET /v1/ConsultaCSV/chassi/{chassi}
create or replace view contract.v_consulta_csv_by_chassi as
  select chassi, coalesce(jsonb_agg(payload order by id), '[]'::jsonb) as payload
  from senatran.consulta_csv
  group by chassi;

-- GET /v1/ConsultaCSV/placa/{placa}
create or replace view contract.v_consulta_csv_by_placa as
  select placa, coalesce(jsonb_agg(payload order by id), '[]'::jsonb) as payload
  from senatran.consulta_csv
  group by placa;

-- GET /v1/indicadores/alarme/chassi/{chassi}
create or replace view contract.v_indicador_alarme_by_chassi as
  select chassi, to_jsonb(ind_alarme) as payload
  from senatran.veiculo;

-- GET /v1/indicadores/alarme/placa/{placa}
create or replace view contract.v_indicador_alarme_by_placa as
  select placa, to_jsonb(ind_alarme) as payload
  from senatran.veiculo;

-- GET /v1/indicadores/restricaoJudicial/chassi/{chassi}
create or replace view contract.v_indicador_restricao_judicial_by_chassi as
  select chassi, jsonb_build_object('indicadorTransferencia', ind_transferencia, 'indicadorLicenciamento', ind_licenciamento, 'indicadorCirculacao', ind_circulacao, 'indicadorPenhora', ind_penhora) as payload
  from senatran.veiculo;

-- GET /v1/indicadores/restricaoJudicial/placa/{placa}
create or replace view contract.v_indicador_restricao_judicial_by_placa as
  select placa, jsonb_build_object('indicadorTransferencia', ind_transferencia, 'indicadorLicenciamento', ind_licenciamento, 'indicadorCirculacao', ind_circulacao, 'indicadorPenhora', ind_penhora) as payload
  from senatran.veiculo;

-- GET /v1/indicadores/rouboFurto/chassi/{chassi}
create or replace view contract.v_indicador_roubo_furto_by_chassi as
  select chassi, to_jsonb(ind_roubo_furto) as payload
  from senatran.veiculo;

-- GET /v1/indicadores/rouboFurto/placa/{placa}
create or replace view contract.v_indicador_roubo_furto_by_placa as
  select placa, to_jsonb(ind_roubo_furto) as payload
  from senatran.veiculo;

-- GET /v1/indicadores/sinistro/chassi/{chassi}
create or replace view contract.v_indicador_sinistro_by_chassi as
  select chassi, jsonb_build_object('indicadorMediaMonta', ind_media_monta, 'indicadorGrandeMonta', ind_grande_monta, 'indicadorRecuperado', ind_recuperado) as payload
  from senatran.veiculo;

-- GET /v1/indicadores/sinistro/placa/{placa}
create or replace view contract.v_indicador_sinistro_by_placa as
  select placa, jsonb_build_object('indicadorMediaMonta', ind_media_monta, 'indicadorGrandeMonta', ind_grande_monta, 'indicadorRecuperado', ind_recuperado) as payload
  from senatran.veiculo;

-- GET /v1/infracoes/ait/{autoInfracao}/orgaoAutuador/{orgao}/infracao/{codigoInfracao}
create or replace view contract.v_infracoes_by_ait as
  select codigo_orgao_autuador, auto_infracao, codigo_infracao, jsonb_build_object('quantidadeInfracoes', count(*), 'quantidadeInfracoesReal', count(*), 'idUltimoRegistro', coalesce(max(id), 0), 'infracoes', coalesce(jsonb_agg(payload order by id), '[]'::jsonb)) as payload
  from senatran.infracao
  group by codigo_orgao_autuador, auto_infracao, codigo_infracao;

-- GET /v1/infracoes/cnpj/{cnpj}
create or replace view contract.v_infracoes_by_cnpj as
  select cnpj, jsonb_build_object('quantidadeInfracoes', count(*), 'quantidadeInfracoesReal', count(*), 'idUltimoRegistro', coalesce(max(id), 0), 'infracoes', coalesce(jsonb_agg(payload order by id), '[]'::jsonb)) as payload
  from senatran.infracao
  group by cnpj;

-- GET /v1/infracoes/cpf/{cpf}
create or replace view contract.v_infracoes_by_cpf as
  select cpf, jsonb_build_object('quantidadeInfracoes', count(*), 'quantidadeInfracoesReal', count(*), 'idUltimoRegistro', coalesce(max(id), 0), 'infracoes', coalesce(jsonb_agg(payload order by id), '[]'::jsonb)) as payload
  from senatran.infracao
  group by cpf;

-- GET /v1/infracoes/habilitacaoEstrangeira/{identificacao}
create or replace view contract.v_infracoes_by_habilitacao_estrangeira as
  select identificacao_hab_estr, jsonb_build_object('quantidadeInfracoes', count(*), 'quantidadeInfracoesReal', count(*), 'idUltimoRegistro', coalesce(max(id), 0), 'infracoes', coalesce(jsonb_agg(payload order by id), '[]'::jsonb)) as payload
  from senatran.infracao
  group by identificacao_hab_estr;

-- GET /v1/infracoes/ocorrencias/ait/{autoInfracao}/orgaoAutuador/{orgao}/infracao/{codigoInfracao}
create or replace view contract.v_infracao_ocorrencias_by_ait as
  select codigo_orgao_autuador, auto_infracao, codigo_infracao, jsonb_build_object('quantidade', count(*), 'quantidadeReal', count(*), 'ocorrencias', coalesce(jsonb_agg(payload order by id), '[]'::jsonb)) as payload
  from senatran.infracao_ocorrencia
  group by codigo_orgao_autuador, auto_infracao, codigo_infracao;

-- GET /v1/infracoes/pagamentos/ait/{autoInfracao}/orgaoAutuador/{orgao}/infracao/{codigoInfracao}
create or replace view contract.v_infracao_pagamentos_by_ait as
  select codigo_orgao_autuador, auto_infracao, codigo_infracao, jsonb_build_object('quantidade', count(*), 'quantidadeReal', count(*), 'pagamentos', coalesce(jsonb_agg(payload order by id), '[]'::jsonb)) as payload
  from senatran.infracao_pagamento
  group by codigo_orgao_autuador, auto_infracao, codigo_infracao;

-- GET /v1/infracoes/pgu/{pgu}/uf/{uf}
create or replace view contract.v_infracoes_by_pgu_and_uf as
  select numero_pgu, uf, jsonb_build_object('quantidadeInfracoes', count(*), 'quantidadeInfracoesReal', count(*), 'idUltimoRegistro', coalesce(max(id), 0), 'infracoes', coalesce(jsonb_agg(payload order by id), '[]'::jsonb)) as payload
  from senatran.infracao
  group by numero_pgu, uf;

-- GET /v1/infracoes/placa/{placa}/exigibilidade/{situacaoExigibilidade}
create or replace view contract.v_infracoes_by_placa_and_exigibilidade as
  select placa, situacao_exigibilidade, jsonb_build_object('quantidadeInfracoes', count(*), 'quantidadeInfracoesReal', count(*), 'idUltimoRegistro', coalesce(max(id), 0), 'infracoes', coalesce(jsonb_agg(payload order by id), '[]'::jsonb)) as payload
  from senatran.infracao
  group by placa, situacao_exigibilidade;

-- GET /v1/infracoes/registroCnh/{cnh}
create or replace view contract.v_infracoes_by_registro_cnh as
  select numero_registro_cnh, jsonb_build_object('quantidadeInfracoes', count(*), 'quantidadeInfracoesReal', count(*), 'idUltimoRegistro', coalesce(max(id), 0), 'infracoes', coalesce(jsonb_agg(payload order by id), '[]'::jsonb)) as payload
  from senatran.infracao
  group by numero_registro_cnh;

-- GET /v1/infracoes/renainf/{numeroRenainf}
create or replace view contract.v_infracoes_by_renainf as
  select codigo_renainf, jsonb_build_object('quantidadeInfracoes', count(*), 'quantidadeInfracoesReal', count(*), 'idUltimoRegistro', coalesce(max(id), 0), 'infracoes', coalesce(jsonb_agg(payload order by id), '[]'::jsonb)) as payload
  from senatran.infracao
  group by codigo_renainf;

-- GET /v1/restricoesJudiciaisAtivas/placa/{placa}
create or replace view contract.v_restricoes_judiciais_ativas_by_placa as
  select placa, jsonb_build_object('quantidadeRetornada', count(*), 'quantidadeReal', count(*), 'idUltimoRegistro', coalesce(max(id), 0), 'processos', coalesce(jsonb_agg(payload order by id), '[]'::jsonb)) as payload
  from senatran.restricao_judicial_processo
  group by placa;

-- GET /v1/restricoesJudiciaisAtivas/placa/{placa}/renavam/{renavam}
create or replace view contract.v_restricoes_judiciais_ativas_by_placa_and_renavam as
  select renavam, placa, jsonb_build_object('quantidadeRetornada', count(*), 'quantidadeReal', count(*), 'idUltimoRegistro', coalesce(max(id), 0), 'processos', coalesce(jsonb_agg(payload order by id), '[]'::jsonb)) as payload
  from senatran.restricao_judicial_processo
  group by renavam, placa;

-- GET /v1/rouboFurto/emAberto/chassi/{chassi}
create or replace view contract.v_roubo_furto_em_aberto_by_chassi as
  select chassi, jsonb_build_object('quantidadeRetornada', count(*), 'quantidadeReal', count(*), 'idUltimoRegistro', coalesce(max(id), 0), 'ocorrenciasRouboFurto', coalesce(jsonb_agg(payload order by id), '[]'::jsonb)) as payload
  from senatran.roubo_furto_ocorrencia
  group by chassi;

-- GET /v1/rouboFurto/emAberto/placa/{placa}
create or replace view contract.v_roubo_furto_em_aberto_by_placa as
  select placa, jsonb_build_object('quantidadeRetornada', count(*), 'quantidadeReal', count(*), 'idUltimoRegistro', coalesce(max(id), 0), 'ocorrenciasRouboFurto', coalesce(jsonb_agg(payload order by id), '[]'::jsonb)) as payload
  from senatran.roubo_furto_ocorrencia
  group by placa;

-- GET /v1/veiculos/cambio/{cambio}
create or replace view contract.v_veiculo_by_cambio as
  select numero_cambio, jsonb_build_object('quantidadeVeiculo', count(*), 'quantidadeVeiculoReal', count(*), 'idUltimoRegistro', coalesce(max(id), 0), 'veiculo', coalesce(jsonb_agg(payload order by id), '[]'::jsonb)) as payload
  from senatran.veiculo
  group by numero_cambio;

-- GET /v1/veiculos/chassi/{chassi}
create or replace view contract.v_veiculo_by_chassi as
  select chassi, jsonb_build_object('quantidadeVeiculo', count(*), 'quantidadeVeiculoReal', count(*), 'idUltimoRegistro', coalesce(max(id), 0), 'veiculo', coalesce(jsonb_agg(payload order by id), '[]'::jsonb)) as payload
  from senatran.veiculo
  group by chassi;

-- GET /v1/veiculos/codigoSegurancaCrv/{codigoSegurancaCrv}/cnpj/{cnpj}/renavam/{renavam}/placa/{placa}
create or replace view contract.v_veiculo_codigo_seguranca_crv_by_cnpj as
  select codigo_seguranca_crv, cnpj, renavam, placa, payload
  from senatran.csv_seguranca;

-- GET /v1/veiculos/codigoSegurancaCrv/{codigoSegurancaCrv}/cpf/{cpf}/renavam/{renavam}/placa/{placa}
create or replace view contract.v_veiculo_codigo_seguranca_crv_by_cpf as
  select codigo_seguranca_crv, cpf, renavam, placa, payload
  from senatran.csv_seguranca;

-- GET /v1/veiculos/comunicacaoVenda/cnpj/{cnpj}/renavam/{renavam}/placa/{placa}
create or replace view contract.v_comunicacao_venda_by_cnpj as
  select cnpj, placa, renavam, payload
  from senatran.comunicacao_venda;

-- GET /v1/veiculos/comunicacaoVenda/cpf/{cpf}/renavam/{renavam}/placa/{placa}
create or replace view contract.v_comunicacao_venda_by_cpf as
  select cpf, placa, renavam, payload
  from senatran.comunicacao_venda;

-- GET /v1/veiculos/enderecoPossuidor/placa/{placa}
create or replace view contract.v_endereco_possuidor_by_placa as
  select placa, payload
  from senatran.endereco_possuidor;

-- GET /v1/veiculos/enderecoPossuidor/placa/{placa}/renavam/{renavam}
create or replace view contract.v_endereco_possuidor_by_placa_and_renavam as
  select renavam, placa, payload
  from senatran.endereco_possuidor;

-- GET /v1/veiculos/motor/{motor}
create or replace view contract.v_veiculo_by_motor as
  select numero_motor, jsonb_build_object('quantidadeVeiculo', count(*), 'quantidadeVeiculoReal', count(*), 'idUltimoRegistro', coalesce(max(id), 0), 'veiculo', coalesce(jsonb_agg(payload order by id), '[]'::jsonb)) as payload
  from senatran.veiculo
  group by numero_motor;

-- GET /v1/veiculos/multaInterestadual/cnpj/{cnpj}/renavam/{renavam}/placa/{placa}
create or replace view contract.v_multa_interestadual_by_cnpj as
  select cnpj, placa, renavam, payload
  from senatran.multa_interestadual;

-- GET /v1/veiculos/multaInterestadual/cpf/{cpf}/renavam/{renavam}/placa/{placa}
create or replace view contract.v_multa_interestadual_by_cpf as
  select cpf, placa, renavam, payload
  from senatran.multa_interestadual;

-- GET /v1/veiculos/placa/{placa}
create or replace view contract.v_veiculo_by_placa as
  select placa, jsonb_build_object('quantidadeVeiculo', count(*), 'quantidadeVeiculoReal', count(*), 'idUltimoRegistro', coalesce(max(id), 0), 'veiculo', coalesce(jsonb_agg(payload order by id), '[]'::jsonb)) as payload
  from senatran.veiculo
  group by placa;

-- GET /v1/veiculos/proprietario/cnpj/{cnpj}/chassi/{chassi}/renavam/{renavam}
create or replace view contract.v_veiculo_by_proprietario_cnpj_chassi_renavam as
  select id_proprietario, tipo_proprietario, chassi, codigo_renavam, payload
  from senatran.veiculo;

-- GET /v1/veiculos/proprietario/cnpj/{cnpj}/placa/{placa}/renavam/{renavam}
create or replace view contract.v_veiculo_by_proprietario_cnpj_placa_renavam as
  select id_proprietario, tipo_proprietario, placa, codigo_renavam, payload
  from senatran.veiculo;

-- GET /v1/veiculos/proprietario/cnpj/{identificacao}
create or replace view contract.v_veiculos_by_proprietario_cnpj as
  select id_proprietario, tipo_proprietario, jsonb_build_object('quantidadeVeiculo', count(*), 'quantidadeVeiculoReal', count(*), 'idUltimoRegistro', coalesce(max(id), 0), 'veiculo', coalesce(jsonb_agg(payload order by id), '[]'::jsonb)) as payload
  from senatran.veiculo
  group by id_proprietario, tipo_proprietario;

-- GET /v1/veiculos/proprietario/cpf/{cpf}/chassi/{chassi}/renavam/{renavam}
create or replace view contract.v_veiculo_by_proprietario_cpf_chassi_renavam as
  select id_proprietario, tipo_proprietario, chassi, codigo_renavam, payload
  from senatran.veiculo;

-- GET /v1/veiculos/proprietario/cpf/{cpf}/placa/{placa}/renavam/{renavam}
create or replace view contract.v_veiculo_by_proprietario_cpf_placa_renavam as
  select id_proprietario, tipo_proprietario, placa, codigo_renavam, payload
  from senatran.veiculo;

-- GET /v1/veiculos/proprietario/cpf/{identificacao}
create or replace view contract.v_veiculos_by_proprietario_cpf as
  select id_proprietario, tipo_proprietario, jsonb_build_object('quantidadeVeiculo', count(*), 'quantidadeVeiculoReal', count(*), 'idUltimoRegistro', coalesce(max(id), 0), 'veiculo', coalesce(jsonb_agg(payload order by id), '[]'::jsonb)) as payload
  from senatran.veiculo
  group by id_proprietario, tipo_proprietario;

-- GET /v1/veiculos/recall/chassi/{chassi}
create or replace view contract.v_veiculo_recall_by_chassi as
  select chassi, payload
  from senatran.recall;

-- GET /v1/veiculos/renavam/{renavam}
create or replace view contract.v_veiculo_by_renavam as
  select codigo_renavam, jsonb_build_object('quantidadeVeiculo', count(*), 'quantidadeVeiculoReal', count(*), 'idUltimoRegistro', coalesce(max(id), 0), 'veiculo', coalesce(jsonb_agg(payload order by id), '[]'::jsonb)) as payload
  from senatran.veiculo
  group by codigo_renavam;
